travis:
  secure:
    BINSTAR_TOKEN: tcIXNacG3+K8Y6F5yC1VpYNiMFL23V/ydzMyoLMZbdFaIBnT3V/p2JSriRdjs8hGWLkukT00s91Z3t02VFgKWvU3Z9z0zkIv+xvtNYNH/oCiFqOV4pnHaXUaW/wfUcO4+2kw5Go5uj/7ANz1oxrtzdyDET9BZ+zof7oMrcWLbsA95JNvTGDTmMnx/VEE7P8q5aYJ1PX5Y5x3JAgisyrAVc4X2nl/C4qwGSFkR0p/K4OYPhxPbFzeGPfJFsnqxmaGll0RorgxAljWYKxfCxaVTr6dlEsS9axACtR0Spr+lf5XAWo4/th8RhQHVYqF1oWfahoMGWQQv177Ar8Tw1+aTliBjb6wvgdg0pEB5dnL6MCQTXlf5OchvHjr3m5Ay8a7lTS7ijnXNCnK7TR4Ggi4TxEGGsqtGNcc3FmXzG5duqJUPX19rBN5RTTp98F0zOg+Y2PRlUW+MyEkE3mb+uE8fxLiq4KuBFsFr2dATdmevF8GSlbRassIL+a0xZtWlLx72OJ6S7UL9ZfcUG6XhsGBfqLE/UZJ1JuVm+4ET5lt8LhsD1RUcGiErS8oRtbxA8RAu30+uPpQFNXFVgLWqCUDXxWJfHbEyTU5hG9t0jzM1PcE/1M9jQa1EhRfs+UyLQoHC3RyHodTXte+dcrYwJueCYQuy0dsfu7jeBTF9cuFFyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
